### ISSUE TITLE
Ask for code

### ISSUE THREAD

**Issue by Yu-xm** [XLiu443/Tem-adapter#1]
Can I ask if it's possible to open-source the code for the paper to facilitate replication?

**Comment by CHENGY12** [comment]
Yes, we will release both training and inference code this week.

**Comment by hxan** [comment]
how is going？

**Comment by hxan** [comment]
hi,how is gonging on

**Comment by CHENGY12** [comment]
Thanks a lot for your attention and sorry for the delay.  We are trying our best to clean the source code and make it more readable. This process is almost done (needs 1~2 days).  We will release them as soon as possible, and let you know at my earliest.  Your patience is highly appreciated.

**Comment by CHENGY12** [comment]
Hi @hxan @Yu-xm , the code is updated!  We highly appreciate your attention to our work and your patience with the code.  Please don't hesitate to drop an email to me or @XLiu443  if you have any issues.
