### ISSUE TITLE
generate h5

### ISSUE THREAD

**Issue by hxan** [XLiu443/Tem-adapter#2]
Hello, could you please provide the h5 file generated after extracting the video? Generating this file takes too much time and takes approximately 8 hours

**Comment by CHENGY12** [comment]
Of course!  Will add a Google Drive link soon! Thanks for this suggestion!

**Comment by XLiu443** [comment]
Hello, we put the h5 file here: https://drive.google.com/drive/folders/1NgfWg6MBD_LYGBXlJqUtlZ52ZEivFSKE?usp=sharing 
Thank you for your patience and feel free to contact us if there are any further questions.
